Parameters:
  NameOfService:
    Description: "The name of the service this stack is to be used for."
    Type: String
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access into the server
    Type: AWS::EC2::KeyPair::KeyName
    Mappings:
  RegionMap:
    eu-west-1:
      AMI: ami-01a6e31ac994bbc09
    eu-west-1:
      AMI: ami-00890f614e48ce866
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId:
        Fn::FindInMap:
        - RegionMap
        - !Ref AWS::Region
        - AMI 
      Tags:
        -  Key: 'Name'
           Value: !Join 
             - " "
             - - 'EC2 in'
               - !Ref AWS::Region
      SecurityGroups:
         -  !Ref MySecurityGroup
      Tags:
         - Key: "Name"
           Value: !Ref NameOfService
      KeyName: !Ref KeyName
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0